//
//  FollowersWorkerTests.swift
//  SafeBoda
//
//  Created by Jalal on 10/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SafeBoda
import XCTest

class FollowersWorkerTests: XCTestCase
{
    // MARK: Subject under test
  
    var sut: FollowersWorker!
  
    // MARK: - Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupFollowersWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup
  
    func setupFollowersWorker() {
        sut = FollowersWorker()
    }

    // MARK: - Test doubles

    // MARK: - Tests
  
    func testSomething() {
        // Given

        // When

        // Then
    }
}
