//
//  FollowingInteractor.swift
//  SafeBoda
//
//  Created by Jalal on 9/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FollowingBusinessLogic {
    func getFollowing(request: Following.GetFollowing.Request)
//    func doSomethingElse(request: Following.SomethingElse.Request)
}

protocol FollowingDataStore {
    var user: AppUser { get set }
}

class FollowingInteractor: FollowingBusinessLogic, FollowingDataStore {
    var presenter: FollowingPresentationLogic?
    var worker: FollowingWorker?
    var user: AppUser = AppUser()

    // MARK: Do something (and send response to FollowingPresenter)

    func getFollowing(request: Following.GetFollowing.Request) {
        worker = FollowingWorker()
        worker?.doCallApiAction(name: user.login ?? "", page: request.page, completionBlock: { list in
            let response = Following.GetFollowing.Response(users: list)
            self.presenter?.presentSomething(response: response)
        })
        
    }
//
//    func doSomethingElse(request: Following.SomethingElse.Request) {
//        worker = FollowingWorker()
//        worker?.doSomeOtherWork()
//
//        let response = Following.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
