//
//  FollowingPresenter.swift
//  SafeBoda
//
//  Created by Jalal on 9/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FollowingPresentationLogic {
    func presentSomething(response: Following.GetFollowing.Response)
}

class FollowingPresenter: FollowingPresentationLogic {
    weak var viewController: FollowingDisplayLogic?

    // MARK: Parse and calc respnse from FollowingInteractor and send simple view model to FollowingViewController to be displayed

    func presentSomething(response: Following.GetFollowing.Response) {
        let viewModel = Following.GetFollowing.ViewModel(users: response.users)
        viewController?.displayResults(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: Following.SomethingElse.Response) {
//        let viewModel = Following.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
