//
//  FollowingWorker.swift
//  SafeBoda
//
//  Created by Jalal on 9/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FollowingWorker {
    func doCallApiAction(name: String, page: Int, completionBlock: @escaping (_ list: [AppUser]) -> Void) {
        ApiManager.shared.GetUserFollowing(name: name, page: page) { success, error, list in
            completionBlock(list)
        }
            // test
    }
//    
//    func doSomeOtherWork() {
//
//    }
}
