//
//  FollowingModels.swift
//  SafeBoda
//
//  Created by Jalal on 9/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Following
{
    // MARK: Use cases

    enum GetFollowing
    {
        struct Request
        {
            var user: AppUser?
            var page: Int = 1
        }

        struct Response
        {
           var users: [AppUser] = []
        }

        struct ViewModel
        {
           var users: [AppUser] = []
        }
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
