//
//  FollowersInteractor.swift
//  SafeBoda
//
//  Created by Jalal on 9/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FollowersBusinessLogic {
    func getFollowers(request: Followers.getFollowers.Request)
//    func doSomethingElse(request: Followers.SomethingElse.Request)
}

protocol FollowersDataStore {
    var user: AppUser { get set }
    
}

class FollowersInteractor: FollowersBusinessLogic, FollowersDataStore {
    var presenter: FollowersPresentationLogic?
    var worker: FollowersWorker?
    var user: AppUser = AppUser()

    // MARK: Do something (and send response to FollowersPresenter)

    func getFollowers(request: Followers.getFollowers.Request) {
        worker = FollowersWorker()
        worker?.doCallApiAction(name: user.login ?? "",page: request.page, completionBlock: { list in
            let response = Followers.getFollowers.Response(list: list)
            self.presenter?.presentSomething(response: response)
        })
        
    }

}
