//
//  StartViewController.swift
//  SafeBoda
//
//  Created by Jalal on 10/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartDisplayLogic: AnyObject
{
    func displayResults(viewModel: Start.CheckLogin.ViewModel)
//    func displaySomethingElse(viewModel: Start.SomethingElse.ViewModel)
}

class StartViewController: UIViewController, StartDisplayLogic {
    var interactor: StartBusinessLogic?
    var router: (NSObjectProtocol & StartRoutingLogic & StartDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup Clean Code Design Pattern 

    private func setup() {
        let viewController = self
        let interactor = StartInteractor()
        let presenter = StartPresenter()
        let router = StartRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
//        doSomethingElse()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(true)
        doSomething()
    }
    
    //MARK: - receive events from UI
    
    //@IBOutlet weak var nameTextField: UITextField!
//
//    @IBAction func someButtonTapped(_ sender: Any) {
//
//    }
//
//    @IBAction func otherButtonTapped(_ sender: Any) {
//
//    }
    
    // MARK: - request data from StartInteractor

    func doSomething() {
        let request = Start.CheckLogin.Request()
        interactor?.checkLoggedin(request: request)
    }

    // MARK: - display view model from StartPresenter

    func displayResults(viewModel: Start.CheckLogin.ViewModel) {
        if !viewModel.isLoggedin {
            self.router?.routeToHome(segue: nil)
        } else {
            self.router?.routeToDetails(segue: nil)
        }
    }

}
