//
//  StartModels.swift
//  SafeBoda
//
//  Created by Jalal on 10/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Start
{
    // MARK: Use cases

    enum CheckLogin
    {
        struct Request
        {
            
        }

        struct Response
        {
           var isLoggedin = false
           var user: AppUser?
        }

        struct ViewModel
        {
            var isLoggedin = false
            var user: AppUser?
        }
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
