//
//  StartWorker.swift
//  SafeBoda
//
//  Created by Jalal on 10/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StartWorker {
    func doCheckLogin(completionBlock: @escaping (_ loggedin: Bool, _ user: AppUser?) -> Void) {
        if let user = DataStore.shared.me, user.id != -1 {
            // user logged in before
            completionBlock(true, user)
        } else {
            // user not logged in before
            completionBlock(false, nil)
        }
    }

}
