//
//  StartInteractor.swift
//  SafeBoda
//
//  Created by Jalal on 10/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartBusinessLogic {
    func checkLoggedin(request: Start.CheckLogin.Request)

}

protocol StartDataStore {
    var user: AppUser? { get set }
}

class StartInteractor: StartBusinessLogic, StartDataStore {
    var presenter: StartPresentationLogic?
    var worker: StartWorker?
    var user: AppUser?

    // MARK: Do something (and send response to StartPresenter)

    func checkLoggedin(request: Start.CheckLogin.Request) {
        worker = StartWorker()
        worker?.doCheckLogin(completionBlock: { success, user in
            let response = Start.CheckLogin.Response(isLoggedin: success, user: user)
            self.user = user
            self.presenter?.presentAnyScreen(response: response)
        })
        
    }

}
