//
//  StartPresenter.swift
//  SafeBoda
//
//  Created by Jalal on 10/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartPresentationLogic {
    func presentAnyScreen(response: Start.CheckLogin.Response)
}

class StartPresenter: StartPresentationLogic {
    weak var viewController: StartDisplayLogic?

    // MARK: Parse and calc respnse from StartInteractor and send simple view model to StartViewController to be displayed

    func presentAnyScreen(response: Start.CheckLogin.Response) {
        let viewModel = Start.CheckLogin.ViewModel(isLoggedin: response.isLoggedin, user: response.user)
        viewController?.displayResults(viewModel: viewModel)
        
    }
//
//    func presentSomethingElse(response: Start.SomethingElse.Response) {
//        let viewModel = Start.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
