//
//  DetailsWorker.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailsWorker {
    func getUserFromCache() -> AppUser?{
        return DataStore.shared.me
    }
//    
//    func doSomeOtherWork() {
//
//    }
}
