//
//  DetailsRouter.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsRoutingLogic {
    func routeToFollowing(segue: UIStoryboardSegue?)
    func routeToFollowers(segue: UIStoryboardSegue?)
}

protocol DetailsDataPassing {
    var dataStore: DetailsDataStore? { get }
}

class DetailsRouter: NSObject, DetailsRoutingLogic, DetailsDataPassing {
    weak var viewController: DetailsViewController?
    var dataStore: DetailsDataStore?

    // MARK: Routing (navigating to other screens)
    func routeToFollowing(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! FollowingViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard.mainStoryboard
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "FollowingViewController") as! FollowingViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    
    func routeToFollowers(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! FollowersViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "FollowersViewController") as! FollowersViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }


    // MARK: Navigation to other screen
    func navigateToSomewhere(source: DetailsViewController, destination: FollowingViewController) {
        source.show(destination, sender: nil)
    }
    
    func navigateToSomewhere(source: DetailsViewController, destination: FollowersViewController) {
        source.show(destination, sender: nil)
    }


    // MARK: Passing data to other screen
    func passDataToSomewhere(source: DetailsDataStore, destination: inout FollowingDataStore) {
        destination.user = source.user
    }
    
    func passDataToSomewhere(source: DetailsDataStore, destination: inout FollowersDataStore) {
        destination.user = source.user
    }
}
