//
//  DetailsInteractor.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func getUser(request: Details.GetUser.Request)
}

protocol DetailsDataStore {
    var user: AppUser { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?
    var user: AppUser = AppUser()

    // MARK: Do something (and send response to DetailsPresenter)

    func getUser(request: Details.GetUser.Request) {
        worker = DetailsWorker()
        self.user = worker?.getUserFromCache() ?? AppUser()
        let response = Details.GetUser.Response(user: user)
        presenter?.presentUser(response: response)
        
    }

}
