//
//  HomePresenter.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentResults(response: Home.CreateSearchAction.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    // MARK: Parse and calc respnse from HomeInteractor and send simple view model to HomeViewController to be displayed

    func presentResults(response: Home.CreateSearchAction.Response) {
        let viewModel = Home.CreateSearchAction.ViewModel()
        viewController?.displaySearchResults(viewModel: viewModel)
    }
    

}
