//
//  HomeInteractor.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func doSearch(request: Home.CreateSearchAction.Request)
//    func doSomethingElse(request: Home.SomethingElse.Request)
}

protocol HomeDataStore {
    var name: String { get set }
    var user: AppUser {get set}
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var name: String = ""
    var user: AppUser = AppUser()

    // MARK: Do something (and send response to HomePresenter)

    func doSearch(request: Home.CreateSearchAction.Request) {
        worker = HomeWorker()
        worker?.doSearchApiAction(name: request.searchFormFields.name, completionBlock: {
            let response = Home.CreateSearchAction.Response()
            self.user = response.user ?? AppUser()
            self.presenter?.presentResults(response: response)
        })
    }

}
