//
//  HomeWorker.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    func doSearchApiAction(name: String, completionBlock: @escaping () -> Void) {
        ApiManager.shared.GetPersonalInfo(name: name) { success, error in
            // test
            
            completionBlock()
        }
    }

}
