//
//  HomeRouter.swift
//  SafeBoda
//
//  Created by Jalal on 9/22/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToPersonalInfo(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?

// MARK: Routing (navigating to other screens)

func routeToPersonalInfo(segue: UIStoryboardSegue?) {
    if let segue = segue {
        let destinationVC = segue.destination as! DetailsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
        let storyboard = UIStoryboard.mainStoryboard
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailsViewController") as! DetailsViewController
        var destinationDS = destinationVC.router!.dataStore!
        var destinationNav = UINavigationController(rootViewController: destinationVC)
        destinationNav.modalPresentationStyle = .fullScreen
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationNav)
    }
}

// MARK: Navigation to other screen

func navigateToSomewhere(source: HomeViewController, destination: UINavigationController) {
    source.show(destination, sender: nil)
}

// MARK: Passing data to other screen

    func passDataToSomewhere(source: HomeDataStore, destination: inout DetailsDataStore) {
       // destination.name = source.name
        destination.user = source.user 
    }
}
